services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proctoring
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: chrislusf/seaweedfs:latest
    command: "server -s3 -dir=/data -s3.port=9000 -ip=minio"
    ports:
      - "9000:9000"   # S3 API
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
